# Setup
title: The Littleroot Blog
tagline: ""
url: https://blog.littleroot.org
paginate: 100
baseurl: ""
permalink: /:categories/:year/:month/:title

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

include: ['_pages']

exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - poole-LICENSE.md
  - README.md
  - CNAME

sass:
  sass_dir: _sass
  style: :compressed

kramdown:
  auto_ids: true
  syntax_highlighter_opts:
    disable: true



# Options

# Specify the author for blog posts
author:
  name: Nishanth Shanmugham
  email: ns@mail.growl.space
